version: '3.8'
services:
  frontend:
    build: ../frontend
    image: mk-dp/frontend
    container_name: mk-dp-fe
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: on-failure

  backend:
    build: ../backend_ts
    image: mk-dp/backend_ts
    container_name: mk-dp-be
    ports:
      - 80:80
    env_file:
      - ../backend_ts/.env
    depends_on:
      - database
    restart: on-failure
  
  database:
    build: ../database
    image: mk-dp/database
    container_name: mk-dp-db
    ports:
      - '5432:5432'
    env_file:
      - ../database/.env